name: Download cache and Upload

on:
  workflow_dispatch:
    inputs:
      cache_key:
        description: 'Cache key'
        required: true
        type: string
      version:
        description: 'Cache hash version'
        required: true
        type: string

jobs:
  cache-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        uses: Andrej730/cache/restore@main
        with:
          # Path won't be actually used, we will match by 'version'.
          path: .
          key: ${{ github.event.inputs.cache_key }}
          version: ${{ github.event.inputs.version }}

      - name: Upload cached folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-artifact
          path: |
            /home/runner/work/**/*.tzst
